### ISSUE TITLE
Not all addresses end in ^

### ISSUE THREAD

**Issue by andrewjkerr** [connorjacobsen/dropmire#11]
I've come across at least two licenses that have addresses that do not end in a carrot. I've seen that they do end in a question mark which might be the better indicator that the address has ended when parsing.

**Comment by connorjacobsen** [comment]
I will have to look into this more. Were they both florida licenses? And if so, were they vertical, horizontal, etc.

**Comment by andrewjkerr** [comment]
Both Florida and both vertical.

**Comment by connorjacobsen** [comment]
Can you get me a text dump for one of these and email it to me?

**Comment by andrewjkerr** [comment]
I could. I'll try to figure out who had them...

~ Andrew

**Comment by connorjacobsen** [comment]
Any update here? @andrewjkerr

**Comment by andrewjkerr** [comment]
No, not yet. I'll try to recover them from Chrome's auto-complete, but no guarantees.
