### ISSUE TITLE
Carrot is not included for max length city

### ISSUE THREAD

**Issue by andrewjkerr** [connorjacobsen/dropmire#17]
We believe the max to be 13 characters

**Comment by andrewjkerr** [comment]
@connorjacobsen I had an issue with a license that this happened to. The beginning of the string looks like this:

`%FLFORT LAUDERDALONGERBEAM`

I checked the rest of the string and it looked to be valid, but an error was thrown.

**Comment by connorjacobsen** [comment]
Is that a valid string?

**Comment by andrewjkerr** [comment]
It should be. "FORT LAUDERDA" hits the 13 character cap that we thought was in place.
