### ISSUE TITLE
Cities with a space in them (i.e. Saint Cloud) are not parsed correctly

### ISSUE THREAD

**Issue by andrewjkerr** [connorjacobsen/dropmire#9]
In the example of Saint Cloud, only Saint is displayed.

**Comment by connorjacobsen** [comment]
This is due to a problem with the regex for the cities, I have this done locally (I think) I will push it soon.

**Comment by andrewjkerr** [comment]
I'm running into an issue that the multiple parts of the city aren't capitalized correctly (ex - Saint Cloud is displayed as Saint cloud). Is this a quick fix?

**Comment by connorjacobsen** [comment]
https://github.com/connorjacobsen/dropmire/issues/15
